version: '3'

services:
  jenkins-master:
    build: master
    image: jenkins-master
    container_name: jenkins-master
    ports:
      - '8080:8080'
      - '443:443'
      - '50000:50000'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
    environment:
      - JAVA_OPTS="-Xmx2g"

volumes:
  jenkins-data:
    driver: local